repo_url: https://misha99fr.github.io/repo
repo_name: SinShalavu
repo_description: >-
   The F-Droid repository for Breezy Weather

repo_keyalias: KEYALIAS

keystore: keystore.keystore

keystorepass: "KEYSTORE_PASS"

keypass: "KEY_PASS"

keydname: KEYDNAME
